name: lents_cli
description: >
  A command-line tool for creating files and directories in Dart and Flutter projects.
version: 0.3.0
repository: https://github.com/lentscode/lents_cli

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables: 
  lents: lents_cli
