name: lents_cli
description: A sample command-line application with basic argument parsing.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables: 
  lents: lents_cli
